---
- name: 批量部署 HwGauge
  hosts: workers
  gather_facts: no
  remote_user: xc

  vars:
    # 显式定义工作目录，CloudLab 中通常是 /users/用户名
    # 如果你不确定，可以登录机器 pwd 看一下，或者改为 /home/xc
    work_dir: "/users/xc"

  tasks:
    - name: 1. 将安装脚本上传到远程机器
      copy:
        src: ../sh/set_env.sh
        dest: "{{ work_dir }}/set_env.sh"  # 使用绝对路径
        mode: '0755'

    - name: 2. 执行安装脚本
      # become: yes 会切换到root目录
      shell: "./set_env.sh -c"
      args:
        chdir: "{{ work_dir }}" # 强制在用户目录下执行
      register: output
      async: 3600
      poll: 10

    - name: 3. 显示脚本输出日志
      debug:
        var: output.stdout_lines

# ansible-playbook -i hosts.ini set_env.yml